# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'html.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 827)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        self.btn_run.setGeometry(QtCore.QRect(30, 630, 89, 25))
        self.btn_run.setObjectName("btn_run")
        self.main_input = QtWidgets.QTextEdit(self.centralwidget)
        self.main_input.setGeometry(QtCore.QRect(30, 170, 971, 441))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 159, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 74, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.main_input.setPalette(palette)
        self.main_input.setObjectName("main_input")
        self.btn_translate_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_translate_file.setGeometry(QtCore.QRect(30, 130, 111, 25))
        self.btn_translate_file.setObjectName("btn_translate_file")
        self.db_name = QtWidgets.QLineEdit(self.centralwidget)
        self.db_name.setGeometry(QtCore.QRect(160, 10, 113, 25))
        self.db_name.setObjectName("db_name")
        self.db_user = QtWidgets.QLineEdit(self.centralwidget)
        self.db_user.setGeometry(QtCore.QRect(160, 40, 113, 25))
        self.db_user.setObjectName("db_user")
        self.db_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.db_pass.setGeometry(QtCore.QRect(160, 70, 113, 25))
        self.db_pass.setObjectName("db_pass")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 101, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 70, 91, 31))
        self.label_4.setObjectName("label_4")
        self.ru = QtWidgets.QCheckBox(self.centralwidget)
        self.ru.setGeometry(QtCore.QRect(350, 10, 41, 23))
        self.ru.setObjectName("ru")
        self.en = QtWidgets.QCheckBox(self.centralwidget)
        self.en.setGeometry(QtCore.QRect(350, 30, 41, 23))
        self.en.setObjectName("en")
        self.de = QtWidgets.QCheckBox(self.centralwidget)
        self.de.setGeometry(QtCore.QRect(350, 70, 41, 23))
        self.de.setObjectName("de")
        self.uk = QtWidgets.QCheckBox(self.centralwidget)
        self.uk.setGeometry(QtCore.QRect(350, 50, 41, 23))
        self.uk.setObjectName("uk")
        self.main_lang = QtWidgets.QComboBox(self.centralwidget)
        self.main_lang.setGeometry(QtCore.QRect(540, 10, 86, 25))
        self.main_lang.setObjectName("main_lang")
        self.main_lang.addItem("")
        self.main_lang.addItem("")
        self.main_lang.addItem("")
        self.main_lang.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 10, 51, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(400, 10, 131, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(720, 10, 151, 21))
        self.label_7.setObjectName("label_7")
        self.l_placeholder = QtWidgets.QLineEdit(self.centralwidget)
        self.l_placeholder.setGeometry(QtCore.QRect(890, 10, 113, 25))
        self.l_placeholder.setObjectName("l_placeholder")
        self.r_placeholder = QtWidgets.QLineEdit(self.centralwidget)
        self.r_placeholder.setGeometry(QtCore.QRect(890, 50, 113, 25))
        self.r_placeholder.setObjectName("r_placeholder")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(720, 50, 161, 21))
        self.label_8.setObjectName("label_8")
        self.btn_save_settings = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_settings.setGeometry(QtCore.QRect(820, 114, 181, 31))
        self.btn_save_settings.setMouseTracking(False)
        self.btn_save_settings.setObjectName("btn_save_settings")
        self.file_path = QtWidgets.QLineEdit(self.centralwidget)
        self.file_path.setGeometry(QtCore.QRect(150, 130, 641, 25))
        self.file_path.setObjectName("file_path")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HTML Translator"))
        self.btn_run.setText(_translate("MainWindow", "Начать"))
        self.btn_translate_file.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_2.setText(_translate("MainWindow", "БД"))
        self.label_3.setText(_translate("MainWindow", "Пользователь"))
        self.label_4.setText(_translate("MainWindow", "Пароль"))
        self.ru.setText(_translate("MainWindow", "ru"))
        self.en.setText(_translate("MainWindow", "en"))
        self.de.setText(_translate("MainWindow", "de"))
        self.uk.setText(_translate("MainWindow", "ua"))
        self.main_lang.setItemText(0, _translate("MainWindow", "ru"))
        self.main_lang.setItemText(1, _translate("MainWindow", "en"))
        self.main_lang.setItemText(2, _translate("MainWindow", "ua"))
        self.main_lang.setItemText(3, _translate("MainWindow", "de"))
        self.label_5.setText(_translate("MainWindow", "Языки"))
        self.label_6.setText(_translate("MainWindow", "Основной язык"))
        self.label_7.setText(_translate("MainWindow", "Левый плейсхолдер"))
        self.label_8.setText(_translate("MainWindow", "Правый плейсхолдер"))
        self.btn_save_settings.setText(_translate("MainWindow", "Сохранить настройки"))


